add slack integration usecase [ER-1669]
bitrise-steplib/steps-slack-message pull request #90
Opened 2024-11-21 16:15 UTC by nyikos-zoltan

https://bitrise.atlassian.net/browse/ER-1669

### Checklist

- [x] I've read and followed the [Contribution Guidelines](https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md)
- [x] `step.yml` and `README.md` is updated with the changes (if needed)

### Version

Requires a *MINOR* [version update](https://semver.org/)

### Context

### Changes

### Investigation details

### Decisions

2024-11-25 10:08 UTC, ofalvai commented on step.yml
>        title: "Slack API token (Webhook or API token is required)"
```suggestion
      title: "Slack API token (One of webhook URL, API token or workspace integration ID is required)"
```

2024-11-25 10:23 UTC, ofalvai requested changes

2024-11-25 10:23 UTC, ofalvai commented on step.yml
> +         To register a **Workspace Slack Integration** see the Integration page in your Workspace settings
Does it have a stable URL? It would be nice to directly link the page from here.

2024-11-25 10:23 UTC, ofalvai commented on step.yml
> +  - bitrise_build_api_token: $BITRISE_BUILD_API_TOKEN
Usually we don't list these as regular inputs, it just adds to the clutter (I don't see a usecase where the user would override these inputs). Feel free to leave these out from the step.yml and just read the env vars in code.

2024-11-25 10:23 UTC, ofalvai commented on main.go
> +	BuildAPIToken string `env:"bitrise_build_api_token,required"`
```suggestion
	BuildAPIToken stepconf.Secret `env:"bitrise_build_api_token,required"`
```
This type ensures that secret filtering masks the value, even if it leaks into the build log accidentally.

2024-11-25 10:23 UTC, ofalvai commented on main.go
> +	BuildURL      string `env:"bitrise_build_url,required"`
```suggestion
	BuildURL      stepconf.Secret `env:"bitrise_build_url,required"`
```

2024-11-25 10:23 UTC, ofalvai commented on main.go
> +	req, err := http.NewRequest("GET", siURL, http.NoBody)
It would be better to use a retry mechanism, we don't add new HTTP-related code without a retry policy nowadays.
You can find our helper here: https://github.com/bitrise-io/go-utils/blob/v1/retry/retryhttp.go
Notice the v1 branch. This is a very old step that hasn't been migrated to the v2 utils packages, feel free to import this v1 util.

2024-11-25 10:23 UTC, ofalvai commented on main.go
> +		body, err := io.ReadAll(resp.Body)
I think a `defer resp.Body.close()` is missing

2024-11-25 10:23 UTC, ofalvai commented on main.go
> +		return "", fmt.Errorf("server error: %s", resp.Status)
nit: would be useful to print the repsonse too

2024-11-25 10:58 UTC, nyikos-zoltan commented on main.go
> +	BuildURL      string `env:"bitrise_build_url,required"`
Why would this need to be a secret? It's just the slug of the build.

2024-11-25 11:05 UTC, ofalvai commented on main.go
> +	BuildURL      string `env:"bitrise_build_url,required"`
I was focusing on `BuildAPIToken`, but it's true that the URL is not a secret, my bad

2024-11-25 14:20 UTC, ofalvai approved these changes

2025-01-13 15:44 UTC, merged

2025-01-13 16:13 UTC, godrei commented on go.mod
> +	github.com/hashicorp/go-retryablehttp v0.7.7 // indirect
`go mod tidy` marks `github.com/hashicorp/go-retryablehttp v0.7.7` a direct dependency.

2025-01-13 16:13 UTC, godrei commented on main.go
> +	BuildAPIToken stepconf.Secret `env:"BITRISE_BUILD_API_TOKEN,required"`
BuildAPIToken and BuildURL are only required if IntegrationID or IntegrationIDOnError is set.

2025-01-13 16:13 UTC, godrei commented on main.go
> +	req, err := retryablehttp.NewRequest("GET", siURL, http.NoBody)
Usually, we create plain HTTP requests, this way we could get rid of the `github.com/hashicorp/go-retryablehttp` direct dependency.

2025-01-13 16:13 UTC, godrei commented on main.go
> +		body, err := io.ReadAll(resp.Body)
The response has an HTML body for an invalid integration ID, which we shouldn't directly print to the build log.

2025-01-13 16:13 UTC, godrei commented on main.go
> +		webhookURL, err = getWebhookURL(inp.BuildURL, integrationID, string(inp.BuildAPIToken))
We should update the returned error message to make it clear what's the issue.